import {
  createCaption,
  getDurationFrames,
  type LectureEpisode,
} from "../templates/xiaoxuelingLecture/types";
import {
  defaultXiaoxuelingBrand,
  snowGirlCharacter,
} from "../templates/xiaoxuelingLecture/presets";

export const vibeCodingEpisode1 = {
  meta: {
    compositionId: "XiaoxuelingVibeCodingEp01",
    fps: 30,
    width: 1080,
    height: 1920,
    durationSeconds: 192,
  },
  brand: {
    ...defaultXiaoxuelingBrand,
    seriesTitle: "小雪灵讲 Vibe Coding",
    chapterTitle: "01. Vibe Coding 到底是什么",
    episodeLabel: "第 1 集",
  },
  character: snowGirlCharacter,
  highlightWords: [
    "Vibe Coding",
    "AI",
    "意图",
    "验证",
    "反馈",
    "收敛",
    "Prompt",
    "目标",
    "对象",
    "约束",
    "验收",
    "README",
    "测试",
  ],
  scenes: [
    {
      id: "cold-open",
      kind: "coldOpen",
      start: 0,
      end: 8,
      label: "Hook",
      eyebrow: "别再用旧姿势理解 AI 编程",
      headline: "不会写代码\n也可能做软件",
      contrastLeft: "旧问题：我会不会写？",
      contrastRight: "新问题：我会不会验？",
      punchline: "前提不是许愿，是验收",
    },
    {
      id: "chapter-map",
      kind: "chapterMap",
      start: 8,
      end: 26,
      label: "本集问题",
      title: "这一集只讲清一件事",
      question: "Vibe Coding 到底是什么？",
      nodes: [
        { label: "定义", caption: "它不是工具，是协作方式" },
        { label: "分工", caption: "人说清意图，AI 执行动作" },
        { label: "闭环", caption: "结果必须被验证和修正" },
      ],
    },
    {
      id: "core-concept",
      kind: "coreConcept",
      start: 26,
      end: 62,
      label: "核心概念",
      title: "一句话定义",
      definition:
        "用自然语言表达意图，让 AI 生成代码、配置和文档，再由人用结果把它拉回正确方向。",
      keywords: ["意图", "执行", "验证", "反馈闭环"],
      formula: ["人描述意图", "AI 执行动作", "人验证结果", "带反馈继续修"],
      warning: "没有验证的 Vibe Coding，只是把问题交给幻觉。",
    },
    {
      id: "analogy",
      kind: "analogy",
      start: 62,
      end: 91,
      label: "通俗类比",
      title: "换个比方",
      analogyTitle: "你不是司机",
      analogy: "你更像导航员 + 验收员。",
      bullets: [
        "告诉 AI 去哪、带什么、别走哪条路",
        "AI 可以开得很快，但不天然知道目的地",
        "到站以后，你要判断结果是不是你要的",
      ],
      bottomNote: "所以会问问题，比会敲字更值钱。",
    },
    {
      id: "engineering",
      kind: "engineering",
      start: 91,
      end: 128,
      label: "工程映射",
      title: "把抽象词翻译成动作",
      mapping: [
        { abstract: "意图", action: "目标是什么" },
        { abstract: "上下文", action: "对象是谁" },
        { abstract: "边界", action: "约束有哪些" },
        { abstract: "验证", action: "怎么验收" },
      ],
      promptBlocks: [
        { label: "目标", text: "给 React 项目加邮箱登录" },
        { label: "对象", text: "登录页、用户状态、退出按钮" },
        { label: "约束", text: "复用现有组件，不改接口" },
        { label: "验收", text: "登录、登出、空邮箱报错都跑通" },
      ],
      principle: "Prompt 不是一句话愿望，而是一份可验收的小需求。",
    },
    {
      id: "mini-demo",
      kind: "miniDemo",
      start: 128,
      end: 170,
      label: "最小流程",
      title: "照着做：4 步闭环",
      steps: [
        {
          label: "1",
          title: "圈目标",
          detail: "先从 README 或需求里标出这次只做什么",
        },
        {
          label: "2",
          title: "写 Prompt",
          detail: "拆成目标、对象、约束、验收四块",
        },
        {
          label: "3",
          title: "让 AI 小步改",
          detail: "只改相关文件，并说明改了哪里",
        },
        {
          label: "4",
          title: "验证再反馈",
          detail: "跑测试、看页面、把错误带回去继续修",
        },
      ],
      readmeLines: [
        "# Login",
        "- 邮箱登录",
        "- 空邮箱提示",
        "- 登录后可退出",
        "- 不改后端接口",
      ],
      terminalLines: [
        { prompt: ">", text: "npm run lint", tone: "normal" },
        { text: "TypeScript ok", tone: "success" },
        { prompt: ">", text: "npm run test:login", tone: "normal" },
        { text: "empty email case failed", tone: "warning" },
        { text: "反馈给 AI：补空邮箱错误态", tone: "success" },
      ],
    },
    {
      id: "pitfall",
      kind: "pitfall",
      start: 170,
      end: 184,
      label: "误区",
      title: "最大的坑：把它当许愿机",
      badTitle: "随便聊",
      goodTitle: "小步验收",
      badItems: ["需求模糊", "一次改太多", "不看结果"],
      goodItems: ["目标收窄", "只改一块", "每步验证"],
      warning: "AI 不是自动正确，它只是自动执行。",
    },
    {
      id: "takeaway",
      kind: "takeaway",
      start: 184,
      end: 192,
      label: "结论",
      title: "本集结论",
      principle: "你不负责替 AI 敲完每行代码，你负责把意图说清楚，并把结果验明白。",
      checklist: ["说清意图", "限制范围", "验证结果"],
      nextTitle: "下一集：怎么真正开始 Vibe Coding",
      signoff: "老铁，开整。",
    },
  ],
  captions: [
    createCaption("以后不会写代码，也可能做软件。", 0, 2.8),
    createCaption("但前提不是会许愿，", 2.8, 5.5),
    createCaption("而是你会验收。", 5.5, 8),
    createCaption("这一集，我们只解决一个问题。", 8, 11),
    createCaption("Vibe Coding 到底是什么？", 11, 14.5),
    createCaption("它不是换一个 AI 工具，", 14.5, 18),
    createCaption("而是把开发分工重新拆一遍。", 18, 22),
    createCaption("人描述意图，AI 执行动作，人负责验证。", 22, 26),
    createCaption("我给你一句定义。", 26, 30),
    createCaption("Vibe Coding 是用自然语言表达意图，", 30, 35),
    createCaption("让 AI 生成代码、配置和文档，", 35, 40),
    createCaption("再由人用测试和结果，把它拉回正确方向。", 40, 45),
    createCaption("所以这件事的核心，不是少写几行代码。", 45, 50),
    createCaption("核心是意图、执行、验证，形成反馈闭环。", 50, 56),
    createCaption("没有验证的 Vibe Coding，只是把问题交给幻觉。", 56, 62),
    createCaption("换个比方，你不是司机。", 62, 66),
    createCaption("你更像导航员加验收员。", 66, 70),
    createCaption("你要告诉 AI 去哪、带什么、不能走哪条路。", 70, 76),
    createCaption("AI 可以开得很快，但它不天然知道目的地。", 76, 81),
    createCaption("到站以后，你还要看结果是不是你要的。", 81, 86),
    createCaption("这就是为什么会问问题，比会敲字更值钱。", 86, 91),
    createCaption("落到工程里，就是一个结构化 Prompt。", 91, 95),
    createCaption("目标是什么，对象是谁，有哪些约束，怎么验收。", 95, 101),
    createCaption("比如不要说，帮我做个登录。", 101, 106),
    createCaption("要说，给 React 项目加邮箱登录。", 106, 110),
    createCaption("包含错误提示、用户状态和退出。", 110, 114),
    createCaption("约束是复用现有组件，不改接口。", 114, 118),
    createCaption("验收是跑通登录、登出和空邮箱报错。", 118, 122),
    createCaption("抽象词一翻译，AI 才知道该往哪执行。", 122, 128),
    createCaption("最小流程可以这样走。", 128, 132),
    createCaption("第一步，先在 README 或需求里圈出当前目标。", 132, 137),
    createCaption("第二步，把目标改写成四块 Prompt。", 137, 142),
    createCaption("第三步，让 AI 只改相关文件，并说明它改了哪里。", 142, 148),
    createCaption("第四步，跑测试、看页面、检查边界情况。", 148, 154),
    createCaption("如果不对，不是重开一局，", 154, 158),
    createCaption("而是带着错误反馈继续修。", 158, 162),
    createCaption("这一步，就是从聊天变成工程闭环。", 162, 166),
    createCaption("你每次反馈，都是在收窄 AI 的搜索范围。", 166, 170),
    createCaption("最大的坑，是把 Vibe Coding 当许愿机。", 170, 174),
    createCaption("随便聊，随便让它改，最后只会越改越乱。", 174, 179),
    createCaption("好做法是小步修改，每一步都验收。", 179, 184),
    createCaption("记住这一句：你不负责替 AI 敲完每行代码。", 184, 188),
    createCaption("你负责把意图说清楚，并把结果验明白。", 188, 191),
    createCaption("下一集讲怎么开工。", 191, 192),
  ],
} satisfies LectureEpisode;

export const vibeCodingEpisode1DurationFrames =
  getDurationFrames(vibeCodingEpisode1);
